name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: "45 18 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'release'
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Release alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: release_haproxy_alpine.Dockerfile
          pull: true
          push: false
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
          # cache-from: type=registry,ref=myorg/myrepository:latest
          # cache-to: type=inline
          # tags: myorg/myrepository:latest
      -
        name: Release debian
        uses: docker/build-push-action@v2
        with:
          context: .
          file: release_haproxy_debian.Dockerfile
          pull: true
          push: false
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
          # cache-from: type=registry,ref=myorg/myrepository:latest
          # cache-to: type=inline
          # tags: myorg/myrepository:latest
